blank_issues_enabled: false
contact_links:
  - name: 页面缺失?
    url: https://slimefun.guizhanss.wiki/#/Expanding-the-Wiki
    about: 欢迎帮我们扩充 Wiki
  - name: QQ 交流群
    url: https://jq.qq.com/?_wv=1027&k=ESbsepYt
    about: 你可以加入粘液科技QQ交流群来获取帮助
    