name: 页面故障
description: 反馈 Wiki 无法正常使用
labels: ['malfunction | 故障']

body:
  - type: markdown
    attributes:
      value: |
        ## 欢迎来到 Slimefun Wiki 问题追踪器
        你正在反馈 Wiki 故障，这通常是由于版本变化或页面改动导致的。
        你可以在阅读[如何扩充Wiki](https://slimefun.guizhanss.wiki/#/Expanding-the-Wiki)后，帮助我们修正这些信息。

        <strong><i>你必须填写标注为星号（*）的表单项</i></strong>

  - id: description
    type: textarea
    validations:
      required: true
    attributes:
      label: '问题描述'
      description: |
        请尽量详细的描述问题，以及复现步骤。
      placeholder: |
        [...] 页面 [...] 不能点击/不能使用， [...]。
