name: Cloudflare

on: 
  push:
    branches:
      - master
    paths:
      - 'pages/*.md'
      - 'images/*'
    
jobs:
  purge:
    name: Purge cache
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
