name: Build and deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Deploy to deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT_TOKEN }}
          publish_dir: ./
          publish_branch: deploy
          user_name: ${{ secrets.BOT_USERNAME }}
          user_email: ${{ secrets.BOT_EMAIL }}
          exclude_assets: '.github,.gitignore,.editorconfig,LICENSE,README.md,renovate.json'
          enable_jekyll: true

      - name: Checkout deploy
        uses: actions/checkout@master
        with:
          ref: deploy

      - name: Upload pages and images to COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: ./
          remote_path: minecraft/plugin/slimefun/wiki/slimefun/
          clean: true
